# Metadata
name: hazel_dart
version: 0.0.1
description: A Dart port of willardf's Hazel Networking Library.

# Refs
homepage: https://github.com/TheNullicorn/hazel-dart
repository: https://github.com/TheNullicorn/hazel-dart
issue_tracker: https://github.com/TheNullicorn/hazel-dart/issues

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  async: ^2.4.2
  quiver: ^2.1.3
  meta: ^1.2.3

dev_dependencies:
  test: ^1.14.4
